### ISSUE TITLE
dist: Freeze dev.css bundles

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-components#1568]
Images in dev version of dist bundles are not freezed now: https://github.com/bem/bem-components-dist/blob/v2/desktop/bem-components.dev.css#L202

**Comment by narqo** [comment]
Don't we want to use more common naming for files, e.g. `library.js` for unminified version and `library.min.js` for minified?

**Comment by tadatuta** [comment]
I think in most cases minified versions will be used anyway so it's convenient to have it as short as possible. And for debug developers just need to add `dev` suffix.

**Comment by narqo** [comment]
The problem is that it's not obvious where this `.dev` suffix should be known from if user needs it. 

As we usually use `_name.js` notation for minified version and there is no `min.js` file I was sure that we just don't have dev version on CDN.

Just look at the list here https://tech.yandex.ru/jslibs/

Anyway, I don't insist.

**Comment by tadatuta** [comment]
That's quite common approach but still there's no consistency there:
- backbone-min.js (minus instead of dot)
- dojo.js and dojo.js.uncompressed.js

We also checked some external libraries and found out that actually everybody choose different filenames. One company even chosen leading underscore for compressed version ;)

**Comment by narqo** [comment]
Ok, now as now how to get dev version I'm fine with current approach. It was just not obvious at first sight.

**Comment by aristov** [comment]
@tadatuta please specify more details in issue description.

**Comment by tadatuta** [comment]
@aristov done
