### ISSUE TITLE
Don't setup some techs when library used on a project

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-components#336]
We were asked to get rid of WARNs which are the result of absence of `bem-pr` when `bem-components` are used on a project.

@narqo, can we do something like:

``` javascript
process.cwd() === environ.PRJ_ROOT && [
        'spec.js',
        'spec.js+browser.js+bemhtml',
        'spec.bemjson.js'
    ].forEach(getTechResolver(techs, BEMPR_TECHS));
```

or find some other way not to setup techs when using `bem-components` as a library?

// cc @ilyar

**Comment by narqo** [comment]
`process.cwd() === environ.PRJ_ROOT` — NOPE!

```
› bem make -r <path/to/project/root> sets
```

...will break everything.

Technically we can use `environ.ENV_ROOT === environ.PRJ_ROOT` but I don't like this solution. Ability not to use all of this "hacks" is one of the reason, why I still prefer bem-pr instead of bem-sets.

If this warnings are too annoying why not to turn them off on the bem-tools level?

**Comment by tadatuta** [comment]
cc @arikon @scf2k

**Comment by ilyar** [comment]
Необходима возможность настройки сборки в двух режимах production и dewelopment.
Зависимости библиотек bem-core, bem-components по умолчанию устанавливаются в режиме npm i --production и если настройка уровней и сборки библиотеки будет иметь такое разделение, будет счастье.

@tadatuta @arikon сейчас это возможно или надо что то сделать для этого?

**Comment by deeonis** [comment]
Won't fix since we use enb as main build tool.
